spring.application.name=KiaEvPlatform
api.key=
api.key.ev-charger=${CHARGING_API_KEY}
api.key.kakao-map=${KAKAO_API_KEY}


aws.region=us-east-1
aws.secretName=ChargingApiKey_Secret

# ==========================================
# 1. MySQL DB 연결 설정
# ==========================================
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# 아래 URL에서 'DB이름' 부분을 실제 생성해두신 MySQL 스키마 이름으로 꼭 변경하세요!
# DB이름은 ? 전까지 입력하면 됩니다. 만든 DB이름으로 바꾸어 주세요
spring.datasource.url=jdbc:mysql://localhost:3306/kiaevdb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
# (본인의 MySQL 아이디, 보통 root)
spring.datasource.username=root
# 본인의 MySQL 비밀번호로 변경하세요!
spring.datasource.password=1234

# ==========================================
# 2. JPA & Hibernate 설정
# ==========================================
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# ddl-auto 속성: Entity 클래스 기반으로 DB 테이블을 자동 생성/수정
spring.jpa.hibernate.ddl-auto=update

# 콘솔창에 JPA가 실행하는 SQL 쿼리를 보기 좋게 출력
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true

