spring.application.name=KiaEvPlatform

# ==========================================
# 1. MySQL DB ì°ê²° ì¤ì 
# ==========================================
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# ìë URLìì 'DBì´ë¦' ë¶ë¶ì ì¤ì  ìì±í´ëì  MySQL ì¤í¤ë§ ì´ë¦ì¼ë¡ ê¼­ ë³ê²½íì¸ì!
# DBì´ë¦ì ? ì ê¹ì§ ìë ¥íë©´ ë©ëë¤. ë§ë  DBì´ë¦ì¼ë¡ ë°ê¾¸ì´ ì£¼ì¸ì
spring.datasource.url=jdbc:mysql://localhost:3306/kiaevdb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
# (ë³¸ì¸ì MySQL ìì´ë, ë³´íµ root)
spring.datasource.username=root
# ë³¸ì¸ì MySQL ë¹ë°ë²í¸ë¡ ë³ê²½íì¸ì!
spring.datasource.password=1234

# ==========================================
# 2. JPA & Hibernate ì¤ì 
# ==========================================
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# ddl-auto ìì±: Entity í´ëì¤ ê¸°ë°ì¼ë¡ DB íì´ë¸ì ìë ìì±/ìì 
spring.jpa.hibernate.ddl-auto=update

# ì½ìì°½ì JPAê° ì¤ííë SQL ì¿¼ë¦¬ë¥¼ ë³´ê¸° ì¢ê² ì¶ë ¥
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true

# 세션 만료 시간
server.servlet.session.timeout=30m